InterventionsConfig:
  intervention_type: "LoreftIntervention" # or "DireftIntervention"
  intervention_layers: "all" # "all" | "odd_only" | "even_only" | "alternate"
  low_rank_dimension: 128
  dropout: 0.0
  act_fn: "gelu" # "gelu", "relu", or null/linear
  init_orth: true